# Generated by Django 5.2.3 on 2025-06-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notecomment_noterating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notecomment',
            old_name='comment',
            new_name='text',
        ),
    ]
