# Generated by Django 5.2.3 on 2025-06-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_rename_comment_notecomment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noterating',
            old_name='rating',
            new_name='value',
        ),
    ]
